### ISSUE TITLE
caught TypeError: Failed to execute 'getPointAtLength' on 'SVGGeometryElement': The provided float value is non-finite. 

### ISSUE THREAD

**Issue by wonx** [wonx/rodalies-tracker#5]
```
caught TypeError: Failed to execute 'getPointAtLength' on 'SVGGeometryElement': The provided float value is non-finite.
    at setMarkers (scriptmap.js:32:28)
    at setTrainMarkers (scriptmap.js:51:3)
    at eventSource.onmessage (scriptmap.js:274:9)
```

Appears in map view because one of the passed positions goes beyond the number of stops of a line (path).

Affected route: R2 Centre. In some cases, values beyond 13 are returned, causing this error.

The source of the problem seems to be how the R2 Centre route is generate, as in some cases an additional station appears (Montcada Bifurcació)
![Screenshot_20230410_233250](https://user-images.githubusercontent.com/2736639/231049356-6965facd-91a2-45cb-82da-b2b7f46a24a9.png)

For some reason, there's a trip in weekdays on R2 that ends up in Montcada Bifurcació, which is not part of the line.

**Comment by wonx** [comment]
Fixed in commit [5ad76d7](https://github.com/wonx/rodalies-tracker/commit/5ad76d7553118e586907845384208d725f0445de).
